project:
  type: website
  output-dir: docs

website:
  title: "Economic History"
  search:
    location: navbar
    type: overlay
  sidebar:
    style: "floating"
    contents: 
    - section: Main Text
      contents: index.qmd
    - section: Additional
      contents: "/*.qmd"
  comments: 
    hypothesis:
      theme: clean
      openSidebar: false


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    df-print: paged